'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const {test}=require('node:test');
test('folder root does not repeat category; nested paths retain clickable parent destinations',()=>{
  const elements=new Map();
  const document={querySelector(selector){if(!elements.has(selector))elements.set(selector,{innerHTML:'',hidden:false,insertAdjacentHTML(_at,value){this.innerHTML+=value;}});return elements.get(selector);}};
  const context=vm.createContext({document,window:{},localStorage:{getItem:()=>null},console});
  const source=fs.readFileSync(path.join(__dirname,'../frontend/app.js'),'utf8').replace(/boot\(\);\s*$/,'');
  vm.runInContext(source+'\nglobalThis.app={state,renderFolders};',context);
  const {state,renderFolders}=context.app;
  Object.assign(state,{section:'assets',projectId:'p',category:'scripts',q:'',folders:[],folderId:null});
  renderFolders();
  assert.equal(elements.get('#sectionTitle').textContent,'文本');
  assert.equal(elements.get('#folderBreadcrumb').hidden,true);
  assert.equal(elements.get('#folderBreadcrumb').innerHTML,'');
  state.folders=[{id:'parent',name:'第一章',category:'scripts',parent_id:null},{id:'child',name:'第一场',category:'scripts',parent_id:'parent'}];
  state.folderId='child';renderFolders();
  const breadcrumb=elements.get('#folderBreadcrumb');
  assert.equal(breadcrumb.hidden,false);
  assert.match(breadcrumb.innerHTML,/data-folder-open="root"/);
  assert.match(breadcrumb.innerHTML,/data-folder-open="parent"/);
  assert.doesNotMatch(breadcrumb.innerHTML,/第一场/);
  assert.equal(elements.get('#sectionTitle').textContent,'第一场');
  state.folderId=null;state.category='all';renderFolders();
  assert.equal(breadcrumb.hidden,false);
  assert.match(breadcrumb.innerHTML,/全部分类中的文件/);
});
