'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {test}=require('node:test'),{execFile}=require('node:child_process'),{promisify}=require('node:util'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'..'),dependencies=path.join(root,'tools/markdown-editor/node_modules');
test('real Chromium live tables render safely, edit source, preserve history and survive IME',async t=>{
  const browser=[process.env.YINGXU_TEST_BROWSER,'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe','C:/Program Files/Microsoft/Edge/Application/msedge.exe'].find(p=>p&&fs.existsSync(p));
  if(!browser||!fs.existsSync(path.join(dependencies,'esbuild'))){t.skip('Requires installed Chromium and locked development dependencies');return;}
  const temporary=fs.mkdtempSync(path.join(os.tmpdir(),'yingxu-live-tables-'));
  t.after(()=>{const resolved=path.resolve(temporary);assert.ok(resolved.startsWith(path.resolve(os.tmpdir())+path.sep)&&path.basename(resolved).startsWith('yingxu-live-tables-'));fs.rmSync(resolved,{recursive:true,force:true,maxRetries:10,retryDelay:100});});
  const source=fs.readFileSync(path.join(root,'frontend/live-markdown-source.mjs'),'utf8');
  const esbuild=require(path.join(dependencies,'esbuild'));
  const bundle=esbuild.buildSync({stdin:{contents:source+'\nwindow.tableTest={EditorView,tablePreview,tableFocus,tableFreeze};',resolveDir:path.join(root,'frontend'),loader:'js'},nodePaths:[dependencies],bundle:true,write:false,platform:'browser',format:'iife'}).outputFiles[0].text;
  fs.writeFileSync(path.join(temporary,'editor.js'),bundle);
  fs.copyFileSync(path.join(root,'frontend/live-markdown.css'),path.join(temporary,'editor.css'));
  const initial='\uFEFF# 中文表格检查\r\n\r\n| **项目** | *交互说明* | 数量 | 安全内容 |\r\n| :--- | :---: | ---: | --- |\r\n| 图片查看 | 转义 a\\|b 和 `Ctrl+滚轮` | 12 | <img src=x onerror=alert(1)> |\r\n| 文稿编辑 | ~~旧说明~~与新说明 | 3 | 中文内容 |\r\n\r\n结束段落\r\n\r\n| 第二表格 | 值 |\r\n| --- | --- |\r\n| 未编辑 | 保留 |\r\n';
  const runner=`(async()=>{
    const results=[],check=(name,ok)=>{results.push({name,ok});if(!ok)throw new Error(name);},tick=()=>new Promise(resolve=>setTimeout(resolve,100));
    const original=${JSON.stringify(initial)},changes=[];
    const api=YingXuMarkdown.create({parent:document.querySelector('#editor'),value:original,onChange:value=>changes.push(value)});
    const view=tableTest.EditorView.findFromDOM(document.querySelector('.cm-editor'));
    await tick();
    const tables=()=>[...document.querySelectorAll('.yx-md-table')];
    check('inactive tables render as block tables',tables().length===2&&tables()[0].querySelectorAll('th').length===4);
    check('alignment follows delimiter',tables()[0].querySelectorAll('th')[1].style.textAlign==='center'&&tables()[0].querySelectorAll('th')[2].style.textAlign==='right');
    check('inline emphasis and code remain readable',!!tables()[0].querySelector('strong')&&!!tables()[0].querySelector('em')&&tables()[0].querySelector('code').textContent==='Ctrl+滚轮');
    check('escaped pipe stays in one cell',tables()[0].querySelectorAll('tbody tr')[0].children.length===4&&tables()[0].textContent.includes('a|b'));
    check('HTML is inert table text',!tables()[0].querySelector('img,script,iframe')&&tables()[0].textContent.includes('<img src=x onerror=alert(1)>'));
    check('rendering leaves BOM CRLF and changes untouched',api.getValue()===original&&changes.length===0);
    tables()[0].querySelector('td').dispatchEvent(new MouseEvent('mousedown',{button:0,bubbles:true,cancelable:true}));await tick();
    check('click reveals only the selected table source',tables().length===1&&view.state.sliceDoc(view.state.selection.main.head,view.state.selection.main.head+4)==='图片查看');
    api.insertText('新增');check('source edit updates Markdown draft',api.getValue().includes('| 新增图片查看 |'));
    api.format('undo');check('undo restores original BOM and CRLF bytes',api.getValue()===original);
    api.setMode('source');check('source mode removes all table widgets',tables().length===0&&api.getValue()===original);
    api.setMode('live');api.revealMatch({from:0,to:0,focus:true});await tick();check('live mode restores inactive tables without writes',tables().length===2&&api.getValue()===original);
    const first=tables()[0];first.focus();first.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}));await tick();
    check('keyboard activation exposes table source',tables().length===1&&view.state.selection.main.head>5);
    const stable=tables()[0],before=view.state.sliceDoc();
    view.contentDOM.dispatchEvent(new CompositionEvent('compositionstart',{data:'中',bubbles:true}));
    check('IME starts guarded composition',api.isComposing());
    view.dispatch({changes:{from:0,insert:'中'},userEvent:'input.type.compose'});
    check('IME maps table decorations without replacing DOM',tables()[0]===stable&&view.state.field(tableTest.tablePreview).frozen);
    let blocked=false;try{api.setMode('source');}catch{blocked=true;}check('mode switches are blocked during IME',blocked);
    view.contentDOM.dispatchEvent(new CompositionEvent('compositionend',{data:'中',bubbles:true}));await new Promise(resolve=>setTimeout(resolve,250));
    check('composition resumes table rendering',!api.isComposing()&&!view.state.field(tableTest.tablePreview).frozen);
    api.format('undo');check('IME edit undo retains source',api.getValue()===before);
    const rows=Array.from({length:130},(_,index)=>'| 第'+index+'项 | '+('中文交互描述，保留文稿与原始文件。'.repeat(4))+' | 可验证 |');
    const long='# 长中文表格\\n\\n| 操作 | 预期行为 | 验证结果 |\\n| --- | --- | --- |\\n'+rows.join('\\n')+'\\n\\n末尾可达';
    api.setValue(long);api.revealMatch({from:0,to:0});document.querySelector('#outside').focus();await tick();
    check('long table keeps every row reachable',tables().length===1&&tables()[0].querySelectorAll('tbody tr').length===130&&tables()[0].textContent.includes('第129项'));
    view.scrollDOM.scrollTop=view.scrollDOM.scrollHeight;await tick();
    const last=tables()[0]?.querySelector('tbody tr:last-child');
    check('last long-table row can be scrolled into view',last&&last.getBoundingClientRect().bottom<=view.scrollDOM.getBoundingClientRect().bottom+5&&view.scrollDOM.scrollTop>0);
    check('table does not overflow the whole page',document.documentElement.scrollWidth<=window.innerWidth);
    const wide='前文\\n\\n|'+Array.from({length:18},(_,i)=>'列'+i).join('|')+'|\\n|'+Array(18).fill('---').join('|')+'|\\n|'+Array(18).fill('内容').join('|')+'|';
    api.setValue(wide);api.revealMatch({from:0,to:0});document.querySelector('#outside').focus();await tick();
    check('wide tables scroll inside their own container',tables()[0].scrollWidth>tables()[0].clientWidth&&document.documentElement.scrollWidth<=window.innerWidth);
    tables()[0].scrollLeft=tables()[0].scrollWidth;
    check('last wide-table column is reachable',tables()[0].querySelector('th:last-child').getBoundingClientRect().right<=tables()[0].getBoundingClientRect().right+2);
    api.setValue('# 工作台交互检查\\n\\n| 操作场景 | 用户预期 | 验收重点 |\\n| :--- | :--- | :--- |\\n'+rows.slice(0,7).join('\\n')+'\\n\\n点击表格可编辑 Markdown 原文。');
    api.revealMatch({from:0,to:0});document.querySelector('#outside').focus();view.scrollDOM.scrollTop=0;await tick();
    document.querySelector('#result').textContent=JSON.stringify(results);
  })().catch(error=>document.querySelector('#result').textContent=JSON.stringify({error:String(error),stack:error.stack}));`;
  fs.writeFileSync(path.join(temporary,'runner.js'),runner);
  fs.writeFileSync(path.join(temporary,'fixture.html'),'<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="editor.css"><style>:root{--bg:#fff;--text:#202427;--accent:#202427;--panel:#fff;--panel-2:#f1f2f3;--line:#d2d7da;--active-line:#f6f7f8;--selection:#d4e0e8}body{margin:0;padding:24px;font:15px "Microsoft YaHei",sans-serif;background:#eff1f3}#editor{height:870px;width:1120px;max-width:calc(100vw - 48px);margin:auto;border:1px solid #d2d7da}#outside{display:block;margin:0 auto 12px}#result{font-size:10px;white-space:pre-wrap}</style><button id="outside">实时预览 · 点击表格编辑源码</button><div id="editor"></div><pre id="result"></pre><script src="editor.js"></script><script src="runner.js"></script>');
  const args=['--headless','--disable-gpu','--no-first-run','--disable-background-networking','--window-size=1300,1100',`--user-data-dir=${path.join(temporary,'profile')}`,'--virtual-time-budget=6000','--dump-dom'];
  if(process.env.YINGXU_TABLE_SCREENSHOT)args.push('--screenshot='+path.resolve(process.env.YINGXU_TABLE_SCREENSHOT));
  args.push(pathToFileURL(path.join(temporary,'fixture.html')).href);
  const {stdout}=await promisify(execFile)(browser,args,{windowsHide:true,timeout:30000,maxBuffer:3*1024*1024});
  const match=stdout.match(/<pre id="result">([^<]+)<\/pre>/);assert.ok(match,stdout.slice(-1500));
  const result=JSON.parse(match[1].replace(/&quot;/g,'"').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>'));
  assert.ok(Array.isArray(result),JSON.stringify(result));assert.equal(result.length,22);for(const row of result)assert.equal(row.ok,true,row.name);
});
